# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import gmaps.datasets
# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
cities_df = pd.read_csv("../output_data/cities.csv")
cities_df.dropna()
cities_df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,cabo san lucas,5,MX,1580236120,60,22.89,-109.91,79.00,8.05
1,port lincoln,0,AU,1580236120,77,-34.73,135.87,65.84,5.46
2,lebu,95,CL,1580236120,54,-37.62,-73.65,67.55,11.79
3,bengkulu,100,ID,1580235920,90,-3.80,102.27,76.12,4.14
4,kruisfontein,0,ZA,1580235908,69,-34.00,24.73,62.96,9.35

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps
gmaps.configure(api_key=g_key)
locations = cities_df[["Lat", "Lng"]]
humidity = cities_df["Humidity"].astype(float)

In [4]:
# Configure gmaps

Heatmap = gmaps.figure(center = [0,0] ,zoom_level = 2)
 
heat_layer = gmaps.heatmap_layer(locations, weights=humidity,
                               dissipating=False, max_intensity=100,
                               point_radius = 4)
Heatmap.add_layer(heat_layer)

Heatmap

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
narrowed_city_df = cities_df.loc[(cities_df['Max Temp']<90) &
                           (cities_df['Max Temp']>60) &
                            (cities_df['Humidity']>45) &
                            (cities_df['Humidity']<70) &
                           (cities_df['Wind Speed']<20) &
                            (cities_df['Wind Speed']>5) &
                           (cities_df['Cloudiness']<50)].reset_index(drop=True)
narrowed_city_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,cabo san lucas,5,MX,1580236120,60,22.89,-109.91,79.00,8.05
1,kruisfontein,0,ZA,1580235908,69,-34.00,24.73,62.96,9.35
2,puerto ayora,40,EC,1580235963,69,-0.74,-90.35,82.40,12.75
3,houma,1,US,1580236126,67,29.60,-90.72,66.00,8.05
4,stephenville,40,US,1580235984,55,32.22,-98.20,64.40,13.87
5,busselton,11,AU,1580235874,51,-33.65,115.33,66.99,5.97
6,san cristobal,40,VE,1580235874,62,7.77,-72.22,84.20,8.05
7,ponta do sol,20,PT,1580236141,63,32.67,-17.10,64.40,5.82
8,requena,20,ES,1580236142,67,39.49,-1.10,62.01,12.75
9,saldanha,4,ZA,1580236146,68,-33.01,17.94,69.80,18.34
10,puerto escondido,20,MX,1580236147,62,15.85,-97.07,84.20,10.29
11,camacha,20,PT,1580236049,67,33.08,-16.33,64.40,8.05
12,walvis bay,2,NaN,1580236161,68,-22.96,14.51,68.00,9.17
13,pochutla,40,MX,1580236163,58,15.74,-96.47,86.00,16.11
14,lompoc,1,US,1580235886,67,34.64,-120.46,66.20,11.41
15,inhambane,0,MZ,1580235895,65,-23.86,35.38,77.00,13.20
16,nouadhibou,0,MR,1580236185,56,20.93,-17.03,71.60,12.75
17,chokwe,34,MZ,1580236186,68,-24.53,32.98,74.95,8.23
18,ellisras,0,ZA,1580236189,48,-23.66,27.74,76.17,8.46
19,natal,40,BR,1580236192,62,-5.79,-35.21,87.80,14.99
20,santa lucia,0,ES,1580236200,63,27.91,-15.54,69.01,5.82
21,taltal,11,CL,1580236207,68,-25.40,-70.48,70.75,8.70
22,juazeiro,40,BR,1580236209,52,-9.41,-40.50,89.60,9.17
23,los llanos de aridane,20,ES,1580236210,68,28.66,-17.92,66.20,6.93
24,mattru,39,SL,1580236210,62,7.62,-11.83,84.81,8.59
25,dwarka,0,IN,1580236210,58,22.24,68.97,68.94,17.27
26,hualmay,39,PE,1580236213,58,-11.10,-77.61,79.68,10.85
27,touros,40,BR,1580236216,62,-5.20,-35.46,87.80,14.99
28,bandar-e lengeh,0,IR,1580235995,67,26.56,54.88,60.80,6.93
29,aden,10,YE,1580236067,61,12.78,45.04,75.00,15.99
30,akyab,0,MM,1580236218,61,20.15,92.90,68.43,11.77
31,lujan,1,AR,1580236221,48,-34.57,-59.10,89.01,8.05
32,maxixe,0,MZ,1580236222,65,-23.86,35.35,77.00,13.20
33,edd,8,ER,1580236224,54,13.93,41.69,81.28,16.22

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:

hotel_df = narrowed_city_df.copy()
hotel_df['Hotel Name'] = ''
hotel_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
0,cabo san lucas,5,MX,1580236120,60,22.89,-109.91,79.00,8.05,
1,kruisfontein,0,ZA,1580235908,69,-34.00,24.73,62.96,9.35,
2,puerto ayora,40,EC,1580235963,69,-0.74,-90.35,82.40,12.75,
3,houma,1,US,1580236126,67,29.60,-90.72,66.00,8.05,
4,stephenville,40,US,1580235984,55,32.22,-98.20,64.40,13.87,
5,busselton,11,AU,1580235874,51,-33.65,115.33,66.99,5.97,
6,san cristobal,40,VE,1580235874,62,7.77,-72.22,84.20,8.05,
7,ponta do sol,20,PT,1580236141,63,32.67,-17.10,64.40,5.82,
8,requena,20,ES,1580236142,67,39.49,-1.10,62.01,12.75,
9,saldanha,4,ZA,1580236146,68,-33.01,17.94,69.80,18.34,
10,puerto escondido,20,MX,1580236147,62,15.85,-97.07,84.20,10.29,
11,camacha,20,PT,1580236049,67,33.08,-16.33,64.40,8.05,
12,walvis bay,2,NaN,1580236161,68,-22.96,14.51,68.00,9.17,
13,pochutla,40,MX,1580236163,58,15.74,-96.47,86.00,16.11,
14,lompoc,1,US,1580235886,67,34.64,-120.46,66.20,11.41,
15,inhambane,0,MZ,1580235895,65,-23.86,35.38,77.00,13.20,
16,nouadhibou,0,MR,1580236185,56,20.93,-17.03,71.60,12.75,
17,chokwe,34,MZ,1580236186,68,-24.53,32.98,74.95,8.23,
18,ellisras,0,ZA,1580236189,48,-23.66,27.74,76.17,8.46,
19,natal,40,BR,1580236192,62,-5.79,-35.21,87.80,14.99,
20,santa lucia,0,ES,1580236200,63,27.91,-15.54,69.01,5.82,
21,taltal,11,CL,1580236207,68,-25.40,-70.48,70.75,8.70,
22,juazeiro,40,BR,1580236209,52,-9.41,-40.50,89.60,9.17,
23,los llanos de aridane,20,ES,1580236210,68,28.66,-17.92,66.20,6.93,
24,mattru,39,SL,1580236210,62,7.62,-11.83,84.81,8.59,
25,dwarka,0,IN,1580236210,58,22.24,68.97,68.94,17.27,
26,hualmay,39,PE,1580236213,58,-11.10,-77.61,79.68,10.85,
27,touros,40,BR,1580236216,62,-5.20,-35.46,87.80,14.99,
28,bandar-e lengeh,0,IR,1580235995,67,26.56,54.88,60.80,6.93,
29,aden,10,YE,1580236067,61,12.78,45.04,75.00,15.99,
30,akyab,0,MM,1580236218,61,20.15,92.90,68.43,11.77,
31,lujan,1,AR,1580236221,48,-34.57,-59.10,89.01,8.05,
32,maxixe,0,MZ,1580236222,65,-23.86,35.35,77.00,13.20,
33,edd,8,ER,1580236224,54,13.93,41.69,81.28,16.22,

In [7]:
params = {
    "radius" : 50000,
    "types": "Hotel",
    "keyword": "Lodging",
    "key": g_key
}

for index, row in hotel_df.iterrows():
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    lat = row['Lat']
    lng = row['Lng']

    # update location key value
    params['location'] = f"{lat},{lng}"
    # make request
    response = requests.get(base_url, params=params).json()
    # extract results
    results = response['results']
    
    try:
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']
    except (IndexError):
        print("Hotel not found... skipping.")
        
hotel_df = hotel_df.dropna()   
   
hotel_df

Hotel not found... skipping.

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
0,cabo san lucas,5,MX,1580236120,60,22.89,-109.91,79.00,8.05,"Esperanza, Auberge Resorts Collection"
1,kruisfontein,0,ZA,1580235908,69,-34.00,24.73,62.96,9.35,Aloe Again Beach Accommodation
2,puerto ayora,40,EC,1580235963,69,-0.74,-90.35,82.40,12.75,Casa Natura Galapagos Lodge
3,houma,1,US,1580236126,67,29.60,-90.72,66.00,8.05,Oak Alley Plantation Bed & Breakfast
4,stephenville,40,US,1580235984,55,32.22,-98.20,64.40,13.87,Inn On The River
5,busselton,11,AU,1580235874,51,-33.65,115.33,66.99,5.97,Pullman Bunker Bay Resort Margaret River Region
6,san cristobal,40,VE,1580235874,62,7.77,-72.22,84.20,8.05,Holiday Inn Cucuta
7,ponta do sol,20,PT,1580236141,63,32.67,-17.10,64.40,5.82,Hotel Porto Mare
8,requena,20,ES,1580236142,67,39.49,-1.10,62.01,12.75,Finca Los Olivos
9,saldanha,4,ZA,1580236146,68,-33.01,17.94,69.80,18.34,Kraalbaai Luxury House Boats
10,puerto escondido,20,MX,1580236147,62,15.85,-97.07,84.20,10.29,Posada Real Puerto Escondido
11,camacha,20,PT,1580236049,67,33.08,-16.33,64.40,8.05,Quinta Splendida Wellness & Botanical Garden
13,pochutla,40,MX,1580236163,58,15.74,-96.47,86.00,16.11,Bahia de la Luna
14,lompoc,1,US,1580235886,67,34.64,-120.46,66.20,11.41,Wine Valley Inn & Cottages
15,inhambane,0,MZ,1580235895,65,-23.86,35.38,77.00,13.20,"Travessia Beach Lodge, Mozambique"
16,nouadhibou,0,MR,1580236185,56,20.93,-17.03,71.60,12.75,Hotel Medina
17,chokwe,34,MZ,1580236186,68,-24.53,32.98,74.95,8.23,Makolwa Tivane
18,ellisras,0,ZA,1580236189,48,-23.66,27.74,76.17,8.46,Sebe Sebe Lodge
19,natal,40,BR,1580236192,62,-5.79,-35.21,87.80,14.99,Esmeralda Praia Hotel
20,santa lucia,0,ES,1580236200,63,27.91,-15.54,69.01,5.82,Hotel Riu Gran Canaria
21,taltal,11,CL,1580236207,68,-25.40,-70.48,70.75,8.70,Hotel casa blanca
22,juazeiro,40,BR,1580236209,52,-9.41,-40.50,89.60,9.17,Quartos De Deda
23,los llanos de aridane,20,ES,1580236210,68,28.66,-17.92,66.20,6.93,Hacienda San Jorge
24,mattru,39,SL,1580236210,62,7.62,-11.83,84.81,8.59,Dohas Hotel And Restaurant
25,dwarka,0,IN,1580236210,58,22.24,68.97,68.94,17.27,Club Mahindra Dwarka
26,hualmay,39,PE,1580236213,58,-11.10,-77.61,79.68,10.85,Hostal Chorrillos Beach
27,touros,40,BR,1580236216,62,-5.20,-35.46,87.80,14.99,POUSADA DIAMANTE
28,bandar-e lengeh,0,IR,1580235995,67,26.56,54.88,60.80,6.93,مسجد روستای زیارت
29,aden,10,YE,1580236067,61,12.78,45.04,75.00,15.99,Goldmohr Hotel
30,akyab,0,MM,1580236218,61,20.15,92.90,68.43,11.77,Shwe Thazin Hotel
31,lujan,1,AR,1580236221,48,-34.57,-59.10,89.01,8.05,Hilton Pilar
32,maxixe,0,MZ,1580236222,65,-23.86,35.35,77.00,13.20,Baleia Bay Resort
33,edd,8,ER,1580236224,54,13.93,41.69,81.28,16.22,

In [8]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [9]:
# Add marker layer ontop of heat map

markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
# Add the layer to the map
Heatmap.add_layer(markers)

# Display Map
Heatmap

Figure(layout=FigureLayout(height='420px'))